services:
    backend:
        build: ./backend
        restart: unless-stopped
        ports:
            - 8081:8081
        networks:
            - back_net
    frontend:
        build: ./frontend
        restart: unless-stopped
        ports:
            - 80:5173
        networks:
            - back_net
        environment:
            NODE_ENV: production
            SITE_HOST: xn----7sba7azakeduc.xn--p1ai
            BACKEND_HOST: http://backend:8081
networks:
    back_net:
        driver: bridge
